vim.o.termguicolors = false

local function hl(group_name, opts)
    vim.api.nvim_set_hl(0, group_name, opts)
end

local colors = vim.g.colors

-- Vim editor Commands
hl("Normal", { ctermfg = colors.base05, ctermbg = colors.base00 })
hl("Bold", { cterm = { bold = true } })
hl("Italic", { cterm = { italic = true } })
hl("Debug", { ctermfg = colors.base08 })
hl("Directory", { ctermfg = colors.base0D })
hl("Error", { ctermfg = colors.base08, ctermbg = colors.base00 })
hl("ErrorMsg", { ctermfg = colors.base08, ctermbg = colors.base00 })
hl("Exception", { ctermfg = colors.base08 })
hl("FoldColumn", { ctermfg = colors.base0C, ctermbg = colors.base00 })
hl("Folded", { ctermfg = colors.base03, ctermbg = colors.base01 })
hl("IncSearch", { ctermfg = colors.base01, ctermbg = colors.base09 })
hl("Macro", { ctermfg = colors.base08 })
hl("MatchParen", { ctermbg = colors.base03 })
hl("ModeMsg", { ctermfg = colors.base0B })
hl("MoreMsg", { ctermfg = colors.base0B })
hl("Question", { ctermfg = colors.base0D })
hl("Search", { ctermfg = colors.base01, ctermbg = colors.base0A })
hl("Substitute", { ctermfg = colors.base01, ctermbg = colors.base0A })
hl("SpecialKey", { ctermfg = colors.base03 })
hl("TooLong", { ctermfg = colors.base08 })
hl("Underlined", { ctermfg = colors.base08 })
hl("Visual", { ctermbg = colors.base02 })
hl("VisualNOS", { ctermfg = colors.base08 })
hl("WarningMsg", { ctermfg = colors.base08 })
hl("WildMenu", { ctermfg = colors.base08, ctermbg = colors.base0A })
hl("Title", { ctermfg = colors.base0D })
hl("Conceal", { ctermfg = colors.base0D, ctermbg = colors.base00 })
hl("Cursor", { ctermfg = colors.base00, ctermbg = colors.base05 })
hl("NonText", { ctermfg = colors.base03 })
hl("LineNr", { ctermfg = colors.base04, ctermbg = colors.base00 })
hl("SignColumn", { ctermfg = colors.base04, ctermbg = colors.base00 })
hl("StatusLine", { ctermfg = colors.base05, ctermbg = colors.base02 })
hl("StatusLineNC", { ctermfg = colors.base04, ctermbg = colors.base01 })
hl("WinBar", { ctermfg = colors.base05 })
hl("WinBarNC", { ctermfg = colors.base04 })
hl("VertSplit", { ctermfg = colors.base05, ctermbg = colors.base00 })
hl("ColorColumn", { ctermbg = colors.base01 })
hl("CursorColumn", { ctermbg = colors.base01 })
hl("CursorLine", { ctermbg = colors.base01 })
hl("CursorLineNr", { ctermfg = colors.base04, ctermbg = colors.base01 })
hl("QuickFixLine", { ctermbg = colors.base01 })
hl("PMenu", { ctermfg = colors.base05, ctermbg = colors.base01 })
hl("PMenuSel", { ctermfg = colors.base01, ctermbg = colors.base05 })
hl("TabLine", { ctermfg = colors.base03, ctermbg = colors.base01 })
hl("TabLineFill", { ctermfg = colors.base03, ctermbg = colors.base01 })
hl("TabLineSel", { ctermfg = colors.base0B, ctermbg = colors.base01 })

-- Standard syntax highlighting
hl("Boolean", { ctermfg = colors.base09 })
hl("Character", { ctermfg = colors.base08 })
hl("Comment", { ctermfg = colors.base03 })
hl("Conditional", { ctermfg = colors.base0E })
hl("Constant", { ctermfg = colors.base09 })
hl("Define", { ctermfg = colors.base0E })
hl("Delimiter", { ctermfg = colors.base0F })
hl("Float", { ctermfg = colors.base09 })
hl("Function", { ctermfg = colors.base0D })
hl("Identifier", { ctermfg = colors.base08 })
hl("Include", { ctermfg = colors.base0D })
hl("Keyword", { ctermfg = colors.base0E })
hl("Label", { ctermfg = colors.base0A })
hl("Number", { ctermfg = colors.base09 })
hl("Operator", { ctermfg = colors.base0E })
hl("PreProc", { ctermfg = colors.base0A })
hl("Repeat", { ctermfg = colors.base0A })
hl("Special", { ctermfg = colors.base0C })
hl("SpecialChar", { ctermfg = colors.base0F })
hl("Statement", { ctermfg = colors.base08 })
hl("StorageClass", { ctermfg = colors.base0A })
hl("String", { ctermfg = colors.base0B })
hl("Structure", { ctermfg = colors.base0E })
hl("Tag", { ctermfg = colors.base0A })
hl("Todo", { ctermfg = colors.base0A, ctermbg = colors.base01 })
hl("Type", { ctermfg = colors.base0A })
hl("Typedef", { ctermfg = colors.base0A })

-- Nvim specific highlighting
hl("NvimInternalError", { ctermfg = colors.base00, ctermbg = colors.base08 })
hl("NormalFloat", { ctermfg = colors.base05, ctermbg = colors.base00 })
hl("FloatBorder", { ctermfg = colors.base05, ctermbg = colors.base00 })
hl("NormalNC", { ctermfg = colors.base05, ctermbg = colors.base00 })
hl("TermCursor", { ctermfg = colors.base00, ctermbg = colors.base05 })
hl("TermCursorNC", { ctermfg = colors.base00, ctermbg = colors.base05 })
hl("User1", { ctermfg = colors.base08, ctermbg = colors.base02 })
hl("User2", { ctermfg = colors.base0E, ctermbg = colors.base02 })
hl("User3", { ctermfg = colors.base05, ctermbg = colors.base02 })
hl("User4", { ctermfg = colors.base0C, ctermbg = colors.base02 })
hl("User5", { ctermfg = colors.base05, ctermbg = colors.base02 })
hl("User6", { ctermfg = colors.base05, ctermbg = colors.base01 })
hl("User7", { ctermfg = colors.base05, ctermbg = colors.base02 })
hl("User8", { ctermfg = colors.base00, ctermbg = colors.base02 })
hl("User9", { ctermfg = colors.base00, ctermbg = colors.base02 })
hl("TreesitterContext", { ctermbg = colors.base01, cterm = { italic = true } })

-- Diff highlighting
hl("DiffAdd", { ctermbg = colors.base00 })
hl("DiffChange", { ctermbg = colors.base00 })
hl("DiffDelete", { ctermbg = colors.base00 })
hl("DiffText", { ctermbg = colors.base01, cterm = { bold = true } })
hl("DiffAdded", { ctermfg = colors.base0B, ctermbg = colors.base00 })
hl("DiffFile", { ctermfg = colors.base08, ctermbg = colors.base00 })
hl("DiffNewFile", { ctermfg = colors.base0B, ctermbg = colors.base00 })
hl("DiffLine", { ctermfg = colors.base0D, ctermbg = colors.base00 })
hl("DiffRemoved", { ctermfg = colors.base08, ctermbg = colors.base00 })

-- Git
hl("gitcommitOverflow", { ctermfg = colors.base08 })
hl("gitcommitSummary", { ctermfg = colors.base0B })
hl("gitcommitComment", { ctermfg = colors.base03 })
hl("gitcommitUntracked", { ctermfg = colors.base03 })
hl("gitcommitDiscarded", { ctermfg = colors.base03 })
hl("gitcommitSelected", { ctermfg = colors.base03 })
hl("gitcommitHeader", { ctermfg = colors.base0E })
hl("gitcommitSelectedType", { ctermfg = colors.base0D })
hl("gitcommitUnmergedType", { ctermfg = colors.base0D })
hl("gitcommitDiscardedType", { ctermfg = colors.base0D })
hl("gitcommitBranch", { ctermfg = colors.base09, cterm = { bold = true } })
hl("gitcommitUntrackedFile", { ctermfg = colors.base0A })
hl("gitcommitUnmergedFile", { ctermfg = colors.base08, cterm = { bold = true } })
hl("gitcommitDiscardedFile", { ctermfg = colors.base08, cterm = { bold = true } })
hl("gitcommitSelectedFile", { ctermfg = colors.base0B, cterm = { bold = true } })

-- GitGutter
hl("GitGutterAdd", { ctermfg = colors.base0B, ctermbg = colors.base00 })
hl("GitGutterChange", { ctermfg = colors.base0D, ctermbg = colors.base00 })
hl("GitGutterDelete", { ctermfg = colors.base08, ctermbg = colors.base00 })
hl("GitGutterChangeDelete", { ctermfg = colors.base0E, ctermbg = colors.base00 })

-- Spelling
hl("SpellBad", { cterm = { undercurl = true } })
hl("SpellLocal", { cterm = { undercurl = true } })
hl("SpellCap", { cterm = { undercurl = true } })
hl("SpellRare", { cterm = { undercurl = true } })
hl("DiagnosticError", { ctermfg = colors.base08 })
hl("DiagnosticWarn", { ctermfg = colors.base0E })
hl("DiagnosticInfo", { ctermfg = colors.base0D })
hl("DiagnosticHint", { ctermfg = colors.base0C })
hl("DiagnosticUnderlineError", { cterm = { undercurl = true } })
hl("DiagnosticUnderlineWarning", { cterm = { undercurl = true } })
hl("DiagnosticUnderlineWarn", { cterm = { undercurl = true } })
hl("DiagnosticUnderlineInformation", { cterm = { undercurl = true } })
hl("DiagnosticUnderlineHint", { cterm = { undercurl = true } })

-- UI
hl("CursorLineNR", { ctermfg = colors.prominent, cterm = { bold = true } })
hl("LineNr", { ctermfg = colors.muted })
hl("WinSeparator", { ctermbg = colors.alt, ctermfg = colors.alt })
hl("ColorColumn", { ctermbg = colors.alt })

-- LSP
hl("LspReferenceText", { cterm = { underline = true } })
hl("LspReferenceRead", { cterm = { underline = true } })
hl("LspReferenceWrite", { cterm = { underline = true } })
hl("LspDiagnosticsDefaultError", { link = "DiagnosticError" })
hl("LspDiagnosticsDefaultWarning", { link = "DiagnosticWarn" })
hl("LspDiagnosticsDefaultInformation", { link = "DiagnosticInfo" })
hl("LspDiagnosticsDefaultHint", { link = "DiagnosticHint" })
hl("LspDiagnosticsUnderlineError", { link = "DiagnosticUnderlineError" })
hl("LspDiagnosticsUnderlineWarning", { link = "DiagnosticUnderlineWarning" })
hl("LspDiagnosticsUnderlineInformation", { link = "DiagnosticUnderlineInformation" })
hl("LspDiagnosticsUnderlineHint", { link = "DiagnosticUnderlineHint" })

-- Treesitter
hl("TSAnnotation", { ctermfg = colors.base0F })
hl("TSAttribute", { ctermfg = colors.base0A })
hl("TSBoolean", { ctermfg = colors.base09 })
hl("TSCharacter", { ctermfg = colors.base08 })
hl("TSComment", { ctermfg = colors.base03, cterm = { italic = true } })
hl("TSConstructor", { ctermfg = colors.base0D })
hl("TSConditional", { ctermfg = colors.base0E })
hl("TSConstant", { ctermfg = colors.base09 })
hl("TSConstBuiltin", { ctermfg = colors.base09, cterm = { italic = true } })
hl("TSConstMacro", { ctermfg = colors.base08 })
hl("TSError", { ctermfg = colors.base08 })
hl("TSException", { ctermfg = colors.base08 })
hl("TSField", { ctermfg = colors.base05 })
hl("TSFloat", { ctermfg = colors.base09 })
hl("TSFunction", { ctermfg = colors.base0D })
hl("TSFuncBuiltin", { ctermfg = colors.base0D, cterm = { italic = true } })
hl("TSFuncMacro", { ctermfg = colors.base08 })
hl("TSInclude", { ctermfg = colors.base0D })
hl("TSKeyword", { ctermfg = colors.base0E })
hl("TSKeywordFunction", { ctermfg = colors.base0E })
hl("TSKeywordOperator", { ctermfg = colors.base0E })
hl("TSLabel", { ctermfg = colors.base0A })
hl("TSMethod", { ctermfg = colors.base0D })
hl("TSNamespace", { ctermfg = colors.base08 })
hl("TSNone", { ctermfg = colors.base05 })
hl("TSNumber", { ctermfg = colors.base09 })
hl("TSOperator", { ctermfg = colors.base05 })
hl("TSParameter", { ctermfg = colors.base05 })
hl("TSParameterReference", { ctermfg = colors.base05 })
hl("TSProperty", { ctermfg = colors.base05 })
hl("TSPunctDelimiter", { ctermfg = colors.base0F })
hl("TSPunctBracket", { ctermfg = colors.base05 })
hl("TSPunctSpecial", { ctermfg = colors.base0F })
hl("TSRepeat", { ctermfg = colors.base0E })
hl("TSString", { ctermfg = colors.base0B })
hl("TSStringRegex", { ctermfg = colors.base0C })
hl("TSStringEscape", { ctermfg = colors.base0C })
hl("TSSymbol", { ctermfg = colors.base0B })
hl("TSTag", { ctermfg = colors.base08 })
hl("TSTagDelimiter", { ctermfg = colors.base0F })
hl("TSText", { ctermfg = colors.base05 })
hl("TSStrong", { cterm = { bold = true } })
hl("TSEmphasis", { ctermfg = colors.base09, cterm = { italic = true } })
hl("TSUnderline", { ctermfg = colors.base00, cterm = { underline = true } })
hl("TSStrike", { ctermfg = colors.base00, cterm = { strikethrough = true } })
hl("TSTitle", { ctermfg = colors.base0D })
hl("TSLiteral", { ctermfg = colors.base09 })
hl("TSURI", { ctermfg = colors.base09, cterm = { underline = true } })
hl("TSType", { ctermfg = colors.base0A })
hl("TSTypeBuiltin", { ctermfg = colors.base0A, cterm = { italic = true } })
hl("TSVariable", { ctermfg = colors.base08 })
hl("TSVariableBuiltin", { ctermfg = colors.base08, cterm = { italic = true } })
hl("TSDefinition", { cterm = { underline = true } })
hl("TSDefinitionUsage", { cterm = { underline = true } })
hl("TSCurrentScope", { cterm = { bold = true } })

-- Hop
hl("HopNextKey", { cterm = { bold = true }, ctermfg = colors.main })
hl("HopNextKey1", { cterm = { bold = true }, ctermfg = colors.subtle })
hl("HopNextKey2", { cterm = { bold = true }, ctermfg = colors.fg })

-- Telescope
hl("TelescopeBorder", { ctermfg = colors.base05, ctermbg = colors.base00 })
hl("TelescopePromptBorder", { ctermfg = colors.base05, ctermbg = colors.base00 })
hl("TelescopePromptNormal", { ctermfg = colors.base05, ctermbg = colors.base00 })
hl("TelescopePromptPrefix", { ctermfg = colors.base05, ctermbg = colors.base00 })
hl("TelescopeNormal", { ctermbg = colors.base00 })
hl("TelescopePreviewTitle", { ctermfg = colors.base01, ctermbg = colors.base0B })
hl("TelescopePromptTitle", { ctermfg = colors.base01, ctermbg = colors.base08 })
hl("TelescopeResultsTitle", { ctermfg = colors.base05, ctermbg = colors.base00 })
hl("TelescopeSelection", { ctermbg = colors.base01 })
hl("TelescopePreviewLine", { ctermbg = colors.base01 })

-- Search
hl("IncSearch", { ctermbg = colors.fg, ctermfg = colors.alt, cterm = { bold = true } })
hl("CurSearch", { ctermbg = colors.main, ctermfg = colors.alt, cterm = { bold = true } })
hl("Search", { ctermbg = colors.black2, ctermfg = "NONE", cterm = { bold = true } })

-- StatusLine
hl("StatusLine", { cterm = { bold = true }, ctermbg = colors.alt })
hl("StatusLineNC", { ctermbg = colors.alt, ctermfg = colors.fg })

-- Gitgutter
hl("GitGutterAddLineNr", { ctermfg = colors.alt, ctermbg = colors.main, cterm = { bold = true } })
hl("GitGutterChangeLineNr", { ctermfg = colors.alt, cterm = { bold = true } })
hl("GitGutterDeleteLineNr", { ctermfg = colors.alt, cterm = { standout = true } })
hl("GitGutterChangeDeleteLineNr", { ctermfg = colors.alt, ctermbg = colors.comment, cterm = { standout = true } })

-- Pmenu
hl("NormalFloat", { cterm = { bold = true }, ctermbg = colors.alt, ctermfg = colors.fg })
hl("PmenuSel", { cterm = { bold = true }, ctermbg = colors.main, ctermfg = colors.alt })

-- Copilot
hl("CopilotSuggestion", { ctermfg = colors.muted })

-- Python
hl("@string.documentation.python", {
    ctermfg = colors.base04,
    ctermbg = "NONE",
    cterm = { italic = true },
})
hl("@variable.python", { ctermfg = colors.fg })
hl("@variable.parameter.python", { ctermfg = colors.base05 })
hl("@type.python", { ctermfg = colors.base06 })
hl("@type.builtin.python", { ctermfg = colors.main })
hl("@constant.builtin.python", { ctermfg = colors.main })
hl("@module.builtin.python", { ctermfg = colors.subtle })
hl("@constant.python", { ctermfg = colors.fg })
hl("@constructor.python", { ctermfg = colors.prominent })
hl("@function.method.call.python", { ctermfg = colors.prominent })
hl("@function.method.python", { ctermfg = colors.prominent })
hl("@function.call.python", { ctermfg = colors.prominent })
hl("@function.python", { ctermfg = colors.prominent })
hl("@function.builtin.python", { ctermfg = colors.gray })
