vim.o.termguicolors = false

local function hl(group_name, opts)
    vim.api.nvim_set_hl(0, group_name, opts)
end

local colors = vim.g.colors

-- Generic
hl("Normal", { ctermfg = colors.foreground, ctermbg = colors.background })
hl("Search", { ctermfg = colors.contrast_bright, cterm = { bold = true, underline = true } })
hl("IncSearch", { ctermfg = colors.contrast_bright, cterm = { bold = true, underline = true } })
hl("Substitute", { ctermbg = colors.noir_9 })
hl("CurSearch", { ctermfg = colors.contrast_bright, cterm = { bold = true } })
hl("Visual", { ctermbg = colors.noir_8 })
hl("SignColumn", { ctermbg = colors.background })
hl("LineNr", { ctermfg = colors.noir_9, ctermbg = colors.background })
hl("EndOfBuffer", { ctermfg = colors.noir_8 })
hl("Comment", { ctermfg = colors.noir_7 })
hl("Constant", { ctermfg = colors.primary })
hl("Character", { ctermfg = colors.noir_5 })
hl("Identifier", { ctermfg = colors.noir_0 })
hl("Statement", { ctermfg = colors.noir_1 })
hl("PreProc", { ctermfg = colors.primary })
hl("Type", { ctermfg = colors.foreground })
hl("Special", { ctermfg = colors.noir_5 })
hl("Error", { ctermfg = colors.primary })
hl("Todo", { ctermfg = colors.primary, ctermbg = colors.noir_8 })
hl("Function", { ctermfg = colors.noir_0, cterm = { bold = true } })
hl("ColorColumn", { ctermbg = colors.noir_8 })
hl("Conceal", { ctermfg = colors.noir_7 })
hl("Cursor", { ctermbg = colors.primary_bright })
hl("CursorColumn", { ctermbg = colors.noir_9 })
hl("CursorLine", { ctermbg = colors.alt })
hl("CursorLineNr", { ctermfg = colors.noir_0, ctermbg = colors.alt })
hl("Directory", { ctermfg = colors.noir_3 })
hl("DiffAdd", { ctermfg = colors.primary, ctermbg = colors.noir_8 })
hl("DiffChange", { ctermfg = colors.noir_0, ctermbg = colors.noir_8 })
hl("DiffDelete", { ctermfg = colors.foreground, ctermbg = colors.noir_8 })
hl("DiffText", { ctermfg = colors.noir_0, ctermbg = colors.noir_7 })
hl("ErrorMsg", { ctermfg = colors.diagnostic_error_text, ctermbg = colors.diagnostic_error })
hl("VertSplit", { ctermfg = colors.noir_8, ctermbg = colors.noir_9 })
hl("WinSeparator", { ctermfg = colors.alt, ctermbg = colors.background })
hl("Folded", { ctermfg = colors.noir_5, ctermbg = colors.noir_8 })
hl("FoldColumn", { ctermfg = colors.noir_7 })
hl("MatchParen", { ctermbg = colors.noir_7 })
hl("MoreMsg", { ctermbg = colors.noir_6 })
hl("NonText", { ctermfg = colors.noir_8 })
hl("Pmenu", { ctermfg = colors.noir_1, ctermbg = colors.alt })
hl("PmenuSel", { ctermfg = colors.noir_0, ctermbg = colors.noir_7 })
hl("PmenuSbar", { ctermbg = colors.noir_8 })
hl("PmenuThumb", { ctermbg = colors.noir_7 })
hl("Question", { ctermfg = colors.noir_1, ctermbg = colors.noir_8 })
hl("SpecialKey", { ctermfg = colors.noir_6 })
hl("SpellBad", { ctermfg = colors.primary })
hl("SpellCap", { ctermfg = colors.noir_0 })
hl("SpellLocal", { ctermfg = colors.noir_5 })
hl("SpellRare", { ctermfg = colors.primary })
hl("StatusLine", { ctermfg = colors.noir_5, ctermbg = colors.noir_8 })
hl("TabLine", { ctermfg = colors.noir_3, ctermbg = colors.noir_8 })
hl("TabLineFill", { ctermbg = colors.noir_8 })
hl("TabLineSel", { ctermfg = colors.noir_2 })
hl("Title", { ctermfg = colors.noir_3 })
hl("VisualNOS", { ctermfg = colors.primary, ctermbg = colors.noir_8 })
hl("WarningMsg", { ctermfg = colors.primary })
hl("WildMenu", { ctermfg = colors.noir_5, ctermbg = colors.noir_8 })
hl("FloatBorder", { ctermfg = colors.noir_7 })
hl("FloatTitle", { ctermfg = colors.noir_0 })
hl("NormalFloat", { ctermfg = colors.noir_4 })

-- Treesitter
hl("@boolean", { ctermfg = colors.primary })
hl("@character", { ctermfg = colors.foreground })
hl("@character.special", { ctermfg = colors.noir_2 })
hl("@comment", { ctermfg = colors.noir_7 })
hl("@conditional", { ctermfg = colors.noir_2 })
hl("@constant", { ctermfg = colors.noir_2 })
hl("@constant.builtin", { ctermfg = colors.noir_2 })
hl("@constant.macro", { ctermfg = colors.primary })
hl("@constructor", { ctermfg = colors.noir_1 })
hl("@debug", { ctermfg = colors.noir_2 })
hl("@define", { ctermfg = colors.noir_2 })
hl("@exception", { ctermfg = colors.noir_2 })
hl("@field", { ctermfg = colors.noir_2 })
hl("@float", { ctermfg = colors.noir_2 })
hl("@function", { ctermfg = colors.foreground, cterm = { bold = true } })
hl("@function.builtin", { ctermfg = colors.noir_2, cterm = { bold = true } })
hl("@function.call", { ctermfg = colors.noir_2, cterm = { bold = true } })
hl("@function.macro", { ctermfg = colors.primary, cterm = { bold = true } })
hl("@include", { ctermfg = colors.noir_6 })
hl("@keyword", { ctermfg = colors.noir_5 })
hl("@keyword.function", { ctermfg = colors.noir_5, cterm = { bold = true } })
hl("@keyword.operator", { ctermfg = colors.noir_6 })
hl("@keyword.return", { ctermfg = colors.noir_0 })
hl("@label", { ctermfg = colors.noir_2 })
hl("@macro", { ctermfg = colors.primary })
hl("@method", { ctermfg = colors.noir_1 })
hl("@method.call", { ctermfg = colors.noir_2 })
hl("@namespace", { ctermfg = colors.noir_2 })
hl("@none", { ctermfg = colors.noir_3 })
hl("@number", { ctermfg = colors.primary })
hl("@operator", { ctermfg = colors.noir_6 })
hl("@parameter", { ctermfg = colors.noir_2 })
hl("@preproc", { ctermfg = colors.noir_2 })
hl("@property", { ctermfg = colors.noir_2 })
hl("@punctuation", { ctermfg = colors.noir_2 })
hl("@punctuation.bracket", { ctermfg = colors.noir_6 })
hl("@punctuation.delimiter", { ctermfg = colors.noir_6 })
hl("@punctuation.special", { ctermfg = colors.primary })
hl("@repeat", { ctermfg = colors.noir_2 })
hl("@storageclass", { ctermfg = colors.noir_2 })
hl("@string", { ctermfg = colors.primary })
hl("@string.escape", { ctermfg = colors.noir_2 })
hl("@string.special", { ctermfg = colors.noir_2 })
hl("@structure", { ctermfg = colors.noir_2 })
hl("@tag", { ctermfg = colors.noir_6 })
hl("@tag.builtin", { ctermfg = colors.noir_6 })
hl("@tag.attribute", { ctermfg = colors.noir_4 })
hl("@tag.delimiter", { ctermfg = colors.noir_3 })
hl("@text.literal", { ctermfg = colors.foreground })
hl("@text.reference", { ctermfg = colors.foreground })
hl("@text.title", { ctermfg = colors.noir_2 })
hl("@text.todo", { ctermfg = colors.noir_2 })
hl("@text.underline", { ctermfg = colors.noir_2 })
hl("@text.uri", { ctermfg = colors.noir_2 })
hl("@type", { ctermfg = colors.noir_2 })
hl("@identifier", { ctermfg = colors.noir_0 })
hl("@type.builtin", { ctermfg = colors.noir_6 })
hl("@type.definition", { ctermfg = colors.noir_2 })
hl("@variable", { ctermfg = colors.foreground })
hl("@variable.builtin", { ctermfg = colors.noir_2 })
hl("@lsp.type.function", { ctermfg = colors.noir_0, cterm = { bold = true } })
hl("@lsp.type.macro", { ctermfg = colors.primary })
hl("@lsp.type.method", { ctermfg = colors.noir_2 })

-- LSP / Diagnostics
hl("LspInlayHint", { ctermfg = colors.noir_6, ctermbg = colors.noir_8 })
hl("DiagnosticError", { ctermfg = colors.error, cterm = { bold = true, italic = true, undercurl = true } })
hl("DiagnosticWarn", { ctermfg = colors.warning, cterm = { bold = true, italic = true, undercurl = true } })
hl("DiagnosticInfo", { ctermfg = colors.info, cterm = { bold = true, italic = true, undercurl = true } })
hl("DiagnosticHint", { ctermfg = colors.hint, cterm = { bold = true, italic = true, undercurl = true } })
hl("DiagnosticSignError", { ctermfg = colors.error })
hl("DiagnosticSignWarn", { ctermfg = colors.warning })
hl("DiagnosticSignInfo", { ctermfg = colors.info })
hl("DiagnosticSignHint", { ctermfg = colors.hint })
hl("DiffAdd", { ctermfg = colors.primary })
hl("DiffChange", { ctermfg = colors.foreground })
hl("DiffDelete", { ctermfg = colors.error })
hl("string", { ctermfg = colors.primary })
hl("String", { ctermfg = colors.primary })

-- StatusLine
hl("StatusLine", { ctermbg = colors.background })

-- Flash
hl("FlashMatch", { ctermfg = colors.primary })
hl("FlashCurrent", { ctermfg = colors.primary_bright })
