# Reference: https://giThub.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true


# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
[mode.main.binding]
    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'

    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-6 = 'move-node-to-workspace 6'
    cmd-shift-7 = 'move-node-to-workspace 7'
    cmd-shift-8 = 'move-node-to-workspace 8'
    cmd-shift-9 = 'move-node-to-workspace 9'

    # i3 wraps focus by default
    cmd-shift-h = 'focus --boundaries-action wrap-around-the-workspace left'
    cmd-shift-k = 'focus --boundaries-action wrap-around-the-workspace down'
    cmd-shift-j = 'focus --boundaries-action wrap-around-the-workspace up'
    cmd-shift-l = 'focus --boundaries-action wrap-around-the-workspace right'

    ctrl-shift-h = 'move left'
    ctrl-shift-j = 'move down'
    ctrl-shift-k = 'move up'
    ctrl-shift-l = 'move right'

    cmd-shift-enter = 'join-with left'
    cmd-shift-f = 'fullscreen'
    cmd-shift-e = 'layout tiles horizontal vertical' 
    cmd-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    alt-r = 'reload-config'

    cmd-shift-r = 'mode resize'

[gaps]
    inner.horizontal = 2
    inner.vertical =   2
    outer.left =       2
    outer.bottom =     2
    outer.top =        2
    outer.right =      2

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'
