# vim:ft=kitty
## name: 
## author: Tywr

# Basic colors
foreground           #e5e9f0
background           #121212
selection_foreground #121212
selection_background #e5e9f0

# Cursor colors
cursor            #e5e9f0
cursor_text_color #121212

# URL underline color when hovering with mouse
url_color #AF875F

# Window border colors and terminal bell colors
active_border_color   #81a1c1
inactive_border_color #4c566a
bell_border_color     #88c0d0
visual_bell_color     none

# Tab bar colors
active_tab_foreground   #3b4252
active_tab_background   #88c0d0
inactive_tab_foreground #e5e9f0
inactive_tab_background #4c566a
tab_bar_background      #3b4252
tab_bar_margin_color    none

# Mark colors (marked text in the terminal)
mark1_foreground #3b4252
mark1_background #88c0d0
mark2_foreground #3b4252
mark2_background #bf616a
mark3_foreground #3b4252
mark3_background #ebcb8b

# The basic 16 colors
# black
color0 #1a1a1a
color8 #5c5e60

# red
color1 #AF875F
color9 #D7AF87

# green
color2  #A3E2F5
color10 #c7edf9

# yellow
color3  #3498D1
color11 #49a2d5

# blue
color4  #308DC2
color12 #3b99ce

# magenta
color5  #96CDE0
color13 #b2dae8

# cyan
color6  #88B6D1
color14 #a0c5da

# white
color7  #e5e9f0
color15 #ffffff

# extra panel colors
color16  #2b2c2c
color17  #38393a
color18  #454647
color19  #515355
color20  #67686b
color21  #7c7e82
color21  #919498
color22  #121212