# vim:ft=kitty
## name: 
## author: Tywr

# Basic colors
foreground           #dcdfe4
background           #121212
selection_foreground #121212
selection_background #dcdfe4

# Cursor colors
cursor            #dcdfe4
cursor_text_color #121212

# URL underline color when hovering with mouse
url_color #af875f

# Window border colors and terminal bell colors
active_border_color   #81a1c1
inactive_border_color #4c566a
bell_border_color     #88c0d0
visual_bell_color     none

# Tab bar colors
active_tab_foreground   #3b4252
active_tab_background   #88c0d0
inactive_tab_foreground #e5e9f0
inactive_tab_background #4c566a
tab_bar_background      #3b4252
tab_bar_margin_color    none

# Mark colors (marked text in the terminal)
mark1_foreground #3b4252
mark1_background #88c0d0
mark2_foreground #3b4252
mark2_background #bf616a
mark3_foreground #3b4252
mark3_background #ebcb8b

# The basic 16 colors
# black
color0 #1a1a1a
color8 #636466

# red
color1 #af875f
color9 #d7af87

# green
color2  #abeaff
color10 #eaf9ff

# yellow
color3  #5CA5E6
color11 #85bcec

# blue
color4  #3D80CC
color12 #5c94d4

# magenta
color5  #A7C6D9
color13 #cfe0ea

# cyan
color6  #7CACD9
color14 #a3c5e4

# white
color7  #dcdfe4
color15 #fffffe

# extra panel colors
color16  #2a2a2b
color17  #363738
color18  #424344
color19  #4f5051
color20  #636466
color21  #78797c
color21  #8c8e91
color22  #121212