foreground   #e4e4e4
background   #000000
cursor       #e4e4e4

color0       #000000
color8       #5f5f5f
color1       #ed73a6
color9       #ed73a6
color2       #69E4E1
color10      #69E4E1
color3       #82E4E2
color11      #82E4E2
color4       #9AE4E2
color12      #9AE4E2
color5       #B3E4E3
color13      #B3E4E3
color6       #CBE4E3
color14      #CBE4E3
color7       #e4e4e4
color15      #e4e4e4
