foreground   #eceff4
background   #0C0D10
cursor       #eceff4

color0       #242933
color8       #4c566a
color1       #88c0d0
color9       #88c0d0
color2       #6991B5
color10      #6991B5
color3       #5e81ac
color11      #5e81ac
color4       #7A97BA
color12      #7A97BA
color5       #97ADC9
color13      #97ADC9
color6       #B3C3D7
color14      #B3C3D7
color7       #eceff4
color15      #eceff4
