[colors.primary]
background = "0x11111b"
foreground = "0xcdd6f4"
dim_foreground = "0x82889e"
bright_foreground = "0xf1f4fc"

[colors.cursor]
cursor = "0xcdd6f4"
text = "0x11111b"

[colors.normal]
black = "0x232430"
red = "0xcba6f7"
green = "0x94e2d5"
yellow = "0xa6e3a1"
blue = "0x94e2d5"
magenta = "0x74c7ec"
cyan = "0x89b4fa"
white = "0xcdd6f4"

[colors.bright]
black = "0x535667"
red = "0xe1cbfa"
green = "0xb1e9e0"
yellow = "0xc2ebbe"
blue = "0xb1e9e0"
magenta = "0x92d3f0"
cyan = "0xaecbfb"
white = "0xf1f4fc"

[[colors.indexed_colors]]
index = 16
color = "0x2d2e3b"

[[colors.indexed_colors]]
index = 17
color = "0x333442"

[[colors.indexed_colors]]
index = 18
color = "0x3e404f"

[[colors.indexed_colors]]
index = 19
color = "0x494c5c"

[[colors.indexed_colors]]
index = 20
color = "0x5c6072"

[[colors.indexed_colors]]
index = 21
color = "0x6f7488"

[[colors.indexed_colors]]
index = 21
color = "0x82889e"

[[colors.indexed_colors]]
index = 22
color = "0x11111b"
