[window]
blur = true
decorations = "none"
opacity = 0.75

[colors]
transparent_background_colors = true

[colors.primary]
background = "0x000000"
foreground = "0xeceff4"

[colors.cursor]
cursor = "0xeceff4"
text = "0x000000"

[colors.normal]
black = "0x0e0e0e"
red = "0xb48ead"
green = "0xb0e3f3"
yellow = "0x81a1c1"
blue = "0xaadceb"
cyan = "0xa3d2e1"
magenta = "0x7795b3"
white = "0xeceff4"

[colors.bright]
black = "0x474849"
red = "0xc0a1bb"
green = "0xd4eff8"
yellow = "0x96b1cb"
blue = "0xcae9f2"
cyan = "0xc0e0ea"
magenta = "0x8aa3bd"
white = "0xffffff"

[[colors.indexed_colors]]
index = 16
color = "0x5f6062"

[[colors.indexed_colors]]
index = 17
color = "0x6b6c6e"

[[colors.indexed_colors]]
index = 18
color = "0x838487"

[[colors.indexed_colors]]
index = 19
color = "0x9a9ca0"

[[colors.indexed_colors]]
index = 20
color = "0xb2b5b8"

[[colors.indexed_colors]]
index = 21
color = "0xcacdd1"