[colors.primary]
background = "0x030405"
foreground = "0xe5e9f0"
dim_foreground = "0x8b8e93"
bright_foreground = "0xffffff"

[colors.cursor]
cursor = "0xe5e9f0"
text = "0x030405"

[colors.normal]
black = "0x101113"
red = "0xa093c7"
green = "0xA3E2F5"
yellow = "0x81a1c1"
blue = "0x5e81ac"
magenta = "0x88c0d0"
cyan = "0xb2cad1"
white = "0xe5e9f0"

[colors.bright]
black = "0x525458"
red = "0xb4a9d2"
green = "0xc7edf9"
yellow = "0x96b1cb"
blue = "0x6f8eb5"
magenta = "0xa0cdd9"
cyan = "0xcadadf"
white = "0xffffff"

[[colors.indexed_colors]]
index = 16
color = "0x252628"

[[colors.indexed_colors]]
index = 17
color = "0x2c2d2f"

[[colors.indexed_colors]]
index = 18
color = "0x393b3d"

[[colors.indexed_colors]]
index = 19
color = "0x47494c"

[[colors.indexed_colors]]
index = 20
color = "0x5e6063"

[[colors.indexed_colors]]
index = 21
color = "0x75777b"

[[colors.indexed_colors]]
index = 21
color = "0x8b8e93"
