[colors.primary]
background = "0x000000"
foreground = "0xe5e9f0"
dim_foreground = "0x8a8d91"
bright_foreground = "0xffffff"

[colors.cursor]
cursor = "0xe5e9f0"
text = "0x000000"

[colors.normal]
black = "0x0d0e0e"
red = "0xa093c7"
green = "0xb0e3f3"
yellow = "0x81a1c1"
blue = "0x5e81ac"
magenta = "0x88c0d0"
cyan = "0x99b3cc"
white = "0xe5e9f0"

[colors.bright]
black = "0x505254"
red = "0xb4a9d2"
green = "0xd4eff8"
yellow = "0x96b1cb"
blue = "0x6f8eb5"
magenta = "0xa0cdd9"
cyan = "0xb0c4d7"
white = "0xffffff"

[[colors.indexed_colors]]
index = 16
color = "0x222324"

[[colors.indexed_colors]]
index = 17
color = "0x292a2b"

[[colors.indexed_colors]]
index = 18
color = "0x37383a"

[[colors.indexed_colors]]
index = 19
color = "0x454648"

[[colors.indexed_colors]]
index = 20
color = "0x5c5e60"

[[colors.indexed_colors]]
index = 21
color = "0x737579"

[[colors.indexed_colors]]
index = 21
color = "0x8a8d91"