[window]
blur = true
decorations = "none"
opacity = 0.85

[colors]
transparent_background_colors = true

[colors.primary]
background = "0x0a0b0e"
foreground = "0xe5e9f0"

[colors.cursor]
cursor = "0xe5e9f0"
text = "0x0a0b0e"

[colors.normal]
black = "0x121319"
red = "0xb48ead"
green = "0xafd5df"
yellow = "0x7192b7"
blue = "0x88c0d0"
cyan = "0x8fbcbb"
magenta = "0x9ccad8"
white = "0xe5e9f0"

[colors.bright]
black = "0x414459"
red = "0xb48ead"
green = "0xafd5df"
yellow = "0x7192b7"
blue = "0x88c0d0"
cyan = "0x8fbcbb"
magenta = "0x9ccad8"
white = "0xeceff4"