[window]
blur = true
decorations = "none"
opacity = 0.85

[colors]
transparent_background_colors = true


[colors.cursor]
cursor = "0xeceff4"
text = "0x08090C"

[colors.primary]
background = "0x08090C"
foreground = "0xeceff4"

[colors.normal]
black = "0x2A2C32"
red = "0x7996BA"
green = "0x93ABC7"
yellow = "0xABC0D5"
blue = "0x88C0D0"
cyan = "0xAFD5DF"
magenta = "0x9CCAD8"
white = "0xeceff4"

[colors.bright]
# Light gray
black = "0x45464B"
# High accent color
red = "0xb48ead"
# Deep blue
green = "0x5e81ac"
# Mellow blue
yellow = "0x7a97ba"
# Lighter gray
blue = "0x38393E"
# Even lighter gray
magenta = "0x525458"
# Lightest gray
cyan = "0x6D6E71"
# Darkest gray
white = "0x1F232B"
