[window]
blur = true
decorations = "none"
opacity = 0.85

[colors]
transparent_background_colors = true

[colors.primary]
background = "#000000"
foreground = "#d1d1d1"

[colors.normal]
black = "#202020"
red = "#0087d7"
green = "#5fafff"
yellow = "#87afd7"
blue = "#af875f"
magenta = "#d7af87"
cyan = "#ffd7af"
white = "#d1d1d1"

[colors.bright]
black = "#505050"
red = "#66DEF9"
green = "#005faf"
yellow = "#5f87af"
blue = "#5f5f5f"
magenta = "#949494"
cyan = "#A8A8A8"
white = "#151515"

[colors.cursor]
cursor = "#d1d1d1"
text = "#151515"
