[window]
blur = true
decorations = "none"
opacity = 0.75

[colors]
transparent_background_colors = true

[colors.primary]
background = "0x000000"
foreground = "0xe4e4e4"

[colors.cursor]
cursor = "0xe4e4e4"
text = "0x000000"

[colors.normal]
black = "0x0d0d0d"
red = "0xaf875f"
green = "0xffd7af"
yellow = "0x5fafff"
blue = "0x0087d7"
magenta = "0xd7af87"
cyan = "0x87afd7"
white = "0xe4e4e4"

[colors.bright]
black = "0x454545"
red = "0xbc9b79"
green = "0xfff7ef"
yellow = "0x93c9fe"
blue = "0x009bf7"
magenta = "0xe4c9ae"
cyan = "0xaec9e4"
white = "0xffffff"

[[colors.indexed_colors]]
index = 16
color = "0x5c5c5c"

[[colors.indexed_colors]]
index = 17
color = "0x676767"

[[colors.indexed_colors]]
index = 18
color = "0x7e7e7e"

[[colors.indexed_colors]]
index = 19
color = "0x959595"

[[colors.indexed_colors]]
index = 20
color = "0xacacac"

[[colors.indexed_colors]]
index = 21
color = "0xc3c3c3"