[general]
import = ["~/.config/colorthemes/alacritty/ice.toml"]
live_config_reload = true

[window]
blur = true
decorations = "Buttonless"
opacity = 0.75
padding = { x = 5, y = 10 }
dynamic_padding = false

[colors]
transparent_background_colors = true

[env]
term = "xterm-256color"

[mouse]
hide_when_typing = false

[terminal.shell]
program = "/bin/zsh"

[cursor]
unfocused_hollow = true
blink_interval = 400
blink_timeout = 0
thickness = 0.35
style.shape = "Beam"
style.blinking = "Always"
vi_mode_style.shape = "Beam"
vi_mode_style.blinking = "Always"


[font.offset]
x = 0
y = 0

# KLARTEXT MONO FONT ----------------------------------------------------------
[font]
# size = 16.5
size = 19.25
normal.family = "KlartextMono Nerd Font"
italic.family = "KlartextMono Nerd Font"
bold_italic.family = "KlartextMono Nerd Font"
normal.style = "Regular"
bold.family = "KlartextMono Nerd Font"
italic.style = "Italic"
bold.style = "Medium"
bold_italic.style = "Medium"
glyph_offset.x = 0
glyph_offset.y = 0

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "+"
mods = "Command|Shift"
