[general]
import = ["~/.config/colorthemes/alacritty/ice.toml"]
live_config_reload = true

[window]
blur = true
decorations = "Buttonless"
opacity = 0.75
padding = { x = 5, y = 10 }
dynamic_padding = false

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = false

[env]
term = "xterm-256color"

[mouse]
hide_when_typing = false

[terminal.shell]
program = "/bin/zsh"

[cursor]
unfocused_hollow = true
blink_interval = 400
blink_timeout = 0
thickness = 0.35
style.shape = "Beam"
style.blinking = "Always"
vi_mode_style.shape = "Beam"
vi_mode_style.blinking = "Always"


[font]
size = 19.5
normal.family = "KlartextMono Nerd Font"
normal.style = "Regular"
italic.style = "Italic"
bold.style = "Medium"
bold_italic.style = "Medium"
offset.x = 0
offset.y = 0

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "+"
mods = "Command|Shift"
